In [ ]:
from google.colab import drive 
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import os
import timeit
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)


In [ ]:
df = pd.DataFrame(columns=['text','label'])
folder = ['Budaya','Ekonomi','Entertaiment','Hukum','Kesehatan','Lifestyle',
          'Otomotif','Pendidikan','Politik','Sport','Tekno','Wisata']

In [ ]:
def savetodf(all_files,folder,label):
  dfn = pd.DataFrame(columns=['text','label'])
  for i in range(len(all_files)):
    path_txt_file = 'drive/MyDrive/AATABISMILLAH/Dataset/'+folder+'/'+all_files[i]
    text = pd.read_fwf(path_txt_file, sep='\n', header=None)[0].str.cat()
    dfn.loc[i] = [text,label]
  return dfn

In [ ]:
start = timeit.default_timer()          
for i in range(len(folder)):
  all_files = os.listdir("drive/MyDrive/AATABISMILLAH/Dataset/"+folder[i]+"/")
  label = int(i)
  dfX = savetodf(all_files,folder[i],label)
  frames = [df, dfX] 
  df = pd.concat(frames).drop_duplicates().reset_index(drop=True)
stop = timeit.default_timer()
lama_eksekusi = stop - start
print("Lama eksekusi: ",lama_eksekusi,"detik")

Lama eksekusi:  210.520203681 detik


In [ ]:
df.head()

text label
0  Menpora Dukung Pianis Cilik asal Kendal yang I...     0
1  Puluhan Seniman Gelar Pameran Bersama �Peradab...     0
2  Budaya Indonesia Pudar karena Ulah Kita Sendir...     0
3  Merawat Pusaka TionghoaLie kim in. Tjia Gwan S...     0
4  Perilaku Berlalu Lintas yang Baik Perlu Dibent...     0

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df['text'], df['label'], test_size=0.2, shuffle=True)

In [ ]:
# Pembentukan tf-idf untuk pembobotan
vectorizer = TfidfVectorizer()
x_train = vectorizer.fit_transform(x_train)
x_test = vectorizer.transform(x_test)

In [ ]:
y_train = y_train.astype('int')
modelknn = KNeighborsClassifier(n_neighbors=5, weights='distance')
modelknn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='distance')

In [ ]:
y_pred = modelknn.predict(x_test)
y_pred

array([ 6,  2,  5,  6,  7,  3,  7,  0,  1,  8,  7,  3,  0, 10,  3,  0,  6,
        5,  8,  8, 11,  5,  4,  4,  1,  4,  6,  2, 10, 10,  1,  7,  2, 11,
        4,  9,  1,  7,  8,  9,  7,  9,  8, 10,  6,  1, 11,  6,  1, 11,  8,
       11,  3, 10,  4,  9,  8,  0,  8, 11,  4, 11,  6,  2,  6,  4, 11,  8,
        3,  8,  9,  4,  9,  0])

In [ ]:
modelknn.predict_proba(x_test)

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.19595893, 0.        , 0.59001019, 0.        , 0.        ,
        0.21403087, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.60047867, 0.        , 0.        , 0.        , 0.        ,
        0.19926839, 0.20025294],
       [0.        , 0.        , 0.        , 0.19600645, 0.        ,
        0.        , 0.60938785, 0.        , 0.        , 0.        ,
        0.        , 0.1946057 ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.40232011, 0.        , 0.39847123,
        0.19920866, 0.        ],
       [0.        , 0.        , 0.        , 0.60414539, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.39585461,
        0.        ,

In [ ]:
y_test

42      1
75      2
150     5
209     6
293     9
       ..
265     8
181     6
345    11
135     4
355    11
Name: label, Length: 74, dtype: object

In [ ]:
yy = np.array(y_test.values.tolist())
print(yy)

[ 1  2  5  6  9  3  1  5  1  5  7  2  0 10  8 10  6  4  8  8 11  5  4  4
  1  4  6  5 10 10  1  7  2 11  4  9  5  7  8  9  0 10  8 10  6  3 11  6
 11  3  9 11  6 10  4  9  8  0  3  1  5  2  6  2  6  4 11  1  3  8  6 11
  4 11]


In [ ]:
y_pred

array([ 6,  2,  5,  6,  7,  3,  7,  0,  1,  8,  7,  3,  0, 10,  3,  0,  6,
        5,  8,  8, 11,  5,  4,  4,  1,  4,  6,  2, 10, 10,  1,  7,  2, 11,
        4,  9,  1,  7,  8,  9,  7,  9,  8, 10,  6,  1, 11,  6,  1, 11,  8,
       11,  3, 10,  4,  9,  8,  0,  8, 11,  4, 11,  6,  2,  6,  4, 11,  8,
        3,  8,  9,  4,  9,  0])

In [ ]:
print(confusion_matrix(yy, y_pred))

[[2 0 0 0 0 0 0 1 0 0 0 0]
 [0 3 0 0 0 0 1 1 1 0 0 1]
 [0 0 3 1 0 0 0 0 0 0 0 1]
 [0 1 0 2 0 0 0 0 1 0 0 1]
 [0 0 0 0 6 1 0 0 0 1 0 0]
 [1 1 1 0 1 2 0 0 1 0 0 0]
 [0 0 0 1 0 0 7 0 0 1 0 0]
 [0 0 0 0 0 0 0 3 0 0 0 0]
 [0 0 0 1 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 0 1 1 3 0 0]
 [1 0 0 0 0 0 0 0 0 1 5 0]
 [1 1 0 0 1 0 0 0 0 0 0 5]]


In [ ]:
print(classification_report(yy,y_pred))

              precision    recall  f1-score   support

           0       0.40      0.67      0.50         3
           1       0.50      0.43      0.46         7
           2       0.75      0.60      0.67         5
           3       0.40      0.40      0.40         5
           4       0.75      0.75      0.75         8
           5       0.67      0.29      0.40         7
           6       0.88      0.78      0.82         9
           7       0.50      1.00      0.67         3
           8       0.60      0.86      0.71         7
           9       0.50      0.60      0.55         5
          10       1.00      0.71      0.83         7
          11       0.62      0.62      0.62         8

    accuracy                           0.64        74
   macro avg       0.63      0.64      0.61        74
weighted avg       0.66      0.64      0.63        74

