<a href="https://colab.research.google.com/github/rickylukman/latihanakhir/blob/main/bismillah_code_TA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive 
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import os
import timeit
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
df = pd.DataFrame(columns=['text','label'])
folder = ['Budaya','Ekonomi','Entertaiment','Hukum','Kesehatan','Lifestyle',
          'Otomotif','Pendidikan','Politik','Sport','Tekno','Wisata']

In [ ]:
def savetodf(all_files,folder,label):
  dfn = pd.DataFrame(columns=['text','label'])
  for i in range(len(all_files)):
    path_txt_file = 'drive/MyDrive/AATABISMILLAH/Dataset/'+folder+'/'+all_files[i]
    text = pd.read_fwf(path_txt_file, sep='\n', header=None)[0].str.cat()
    dfn.loc[i] = [text,label]
  return dfn

In [ ]:
start = timeit.default_timer()          
for i in range(len(folder)):
  all_files = os.listdir("drive/MyDrive/AATABISMILLAH/Dataset/"+folder[i]+"/")
  label = int(i)
  dfX = savetodf(all_files,folder[i],label)
  frames = [df, dfX] 
  df = pd.concat(frames).drop_duplicates().reset_index(drop=True)
stop = timeit.default_timer()
lama_eksekusi = stop - start
print("Lama eksekusi: ",lama_eksekusi,"detik")

Lama eksekusi:  125.90874734200003 detik


In [ ]:
df.head()

text label
0  Menpora Dukung Pianis Cilik asal Kendal yang I...     0
1  Puluhan Seniman Gelar Pameran Bersama �Peradab...     0
2  Budaya Indonesia Pudar karena Ulah Kita Sendir...     0
3  Merawat Pusaka TionghoaLie kim in. Tjia Gwan S...     0
4  Perilaku Berlalu Lintas yang Baik Perlu Dibent...     0

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df['text'], df['label'], test_size=0.2, shuffle=True)

In [ ]:
# Pembentukan tf-idf untuk pembobotan
vectorizer = TfidfVectorizer()
x_train = vectorizer.fit_transform(x_train)
x_test = vectorizer.transform(x_test)

In [ ]:
y_train = y_train.astype('int')
modelknn = KNeighborsClassifier(n_neighbors=5, weights='distance')
modelknn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='distance')

In [ ]:
y_pred = modelknn.predict(x_test)
y_pred

array([ 8,  6,  7,  1, 11, 10,  6,  6,  5,  5,  4,  5,  8,  4,  5,  0,  8,
        4,  9,  3,  2,  6,  9,  4, 11,  0,  3, 11,  6,  5, 10, 10,  1, 11,
        8,  2,  9,  5,  1,  2, 10,  6,  7,  8,  8, 11,  5,  0,  7,  1,  2,
        9, 11,  3,  7,  9,  8,  4,  7,  7,  5,  6,  7,  7,  2,  8, 11,  7,
       11,  8,  7,  6, 11,  3])

In [ ]:
modelknn.predict_proba(x_test)

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.19836103, 0.        , 0.        , 0.        ,
        0.        , 0.41220073, 0.        , 0.        , 0.38943824,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.80251851, 0.19748149, 0.        ,
        0.        , 0.        ],
       [0.        , 0.61771876, 0.        , 0.38228124, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.20292804, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.79707196],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.20200978, 0.        , 0.        , 0.        ,
        0.79799022,

In [ ]:
y_test

259    8
181    6
217    7
55     1
7      0
Name: label, dtype: object

In [ ]:
yy = np.array(y_test.values.tolist())
print(yy)
# arrcob = []
# for i in range(len(y_test)):
#   arrcob.append(y_test.loc[i])
# print(arrcob)

[ 8  6  7  1  0 10  6  6  5  4  7  5  8  5  5  0  0  4  0  3  0  6  9  4
 11  0  3 11  6  2 10  1  1  8  3  2  9  5  1  2 10  6  0  8  8 11  4  5
  3  1  7 10 11  3  7  9  4  4  7  7  5  6  7  0  5  8 11  7 11  8  8  6
 11  3]


In [ ]:
y_pred

array([ 8,  6,  7,  1, 11, 10,  6,  6,  5,  5,  4,  5,  8,  4,  5,  0,  8,
        4,  9,  3,  2,  6,  9,  4, 11,  0,  3, 11,  6,  5, 10, 10,  1, 11,
        8,  2,  9,  5,  1,  2, 10,  6,  7,  8,  8, 11,  5,  0,  7,  1,  2,
        9, 11,  3,  7,  9,  8,  4,  7,  7,  5,  6,  7,  7,  2,  8, 11,  7,
       11,  8,  7,  6, 11,  3])

In [ ]:
print(confusion_matrix(yy, y_pred))

[[2 0 1 0 0 0 0 2 1 1 0 1]
 [0 4 0 0 0 0 0 0 0 0 1 0]
 [0 0 2 0 0 1 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 1 1 0 0 0]
 [0 0 0 0 3 2 0 0 1 0 0 0]
 [1 0 1 0 1 5 0 0 0 0 0 0]
 [0 0 0 0 0 0 8 0 0 0 0 0]
 [0 0 1 0 1 0 0 6 0 0 0 0]
 [0 0 0 0 0 0 0 1 6 0 0 1]
 [0 0 0 0 0 0 0 0 0 3 0 0]
 [0 0 0 0 0 0 0 0 0 1 3 0]
 [0 0 0 0 0 0 0 0 0 0 0 7]]


In [ ]:
print(classification_report(yy,y_pred))

              precision    recall  f1-score   support

           0       0.67      0.25      0.36         8
           1       1.00      0.80      0.89         5
           2       0.40      0.67      0.50         3
           3       1.00      0.67      0.80         6
           4       0.60      0.50      0.55         6
           5       0.62      0.62      0.62         8
           6       1.00      1.00      1.00         8
           7       0.60      0.75      0.67         8
           8       0.67      0.75      0.71         8
           9       0.60      1.00      0.75         3
          10       0.75      0.75      0.75         4
          11       0.78      1.00      0.88         7

    accuracy                           0.72        74
   macro avg       0.72      0.73      0.71        74
weighted avg       0.74      0.72      0.71        74

